<!DOCTYPE html>
<html>

<head>

</head>

<body>
    <script>
       

        function fetchBypromise(fileName) {
            return new Promise((resolve, reject) => {
                // Assuming some condition to determine success or failure
                const isError = false; // Change this to true to see the error handling

               
                    reject('Error reading:');
                
            });
        }

        // Using async/await with a catch block
        async function twoSeries(file1, file2, ansArray) {
            try {

                const content1 = await fetchBypromise(file1);
                ansArray.push(content1);

                const content2 = await fetchBypromise(file2);
                ansArray.push(content2);

                ansArray.push('All files have been read');
            } catch (err) {
                console.error(err);
            }
        }

        // Using regular promise
        fetchBypromise('SampleFile')
            .then((content) => {
                console.log(content);
            })
            .catch((err) => {
                console.log(err);
            });

        // Example usage with async/await
        let ansArray = [];
        twoSeries('FILE1', 'FILE2', ansArray).then(() => {
            console.log(ansArray);
        });
    </script>
</body>

</html>